---
version: "2.0"
services:
  app:
    image: laserkit/schnell:0.0.1
    expose:
      - port: 7860
        as: 7860
        to:
          - global: true
profiles:
  compute:
    app:
      resources:
        cpu:
          units: 4
        memory:
          size: 32GB
        storage:
          - size: 40GB
        gpu:
          units: 1
          attributes:
            vendor:
              nvidia: 
  placement:
    dcloud:
      pricing:
        app:
          denom: uakt
          amount: 10000
deployment:
  app:
    dcloud:
      profile: app
      count: 1
